//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CADCommTools.rc
//
#define IDS_PROJNAME                    100
#define IDC_LIST_TEXTCROSSREPORT        100
#define IDC_GRID                        101
#define IDC_LIST_LAYER                  103
#define IDD_DIALOG_LINECROSS            104
#define IDC_CHECK_ALLLAYER              104
#define IDD_DIALOG_SIMPLESEL            105
#define IDC_LIST_TYPE                   105
#define IDC_CHECK_ALLTYPE               106
#define IDD_DIALOG_PURGE                106
#define IDC_BUTTON_LAYERALL             107
#define IDD_DIALOG_MOUSEPREVIEW         107
#define IDC_BUTTON_LAYERALLNOT          108
#define IDD_DIALOG_REG                  108
#define IDC_BUTTON_LAYERFX              109
#define IDC_BUTTON_ENTALL               110
#define IDC_BUTTON_TYPEALL              110
#define IDD_DIALOG_QRCODE               110
#define IDC_BUTTON_ENTALLNOT            111
#define IDC_BUTTON_TYPEALLNOT           111
#define IDD_DIALOG_BARCODE              111
#define IDC_BUTTON6                     112
#define IDC_BUTTON_ENTFX                112
#define IDC_BUTTON_TYPEFX               112
#define IDC_BUTTON_PURGE                112
#define IDD_DIALOG_TEXTBRUSH            112
#define IDC_RADIO_SEL                   113
#define IDC_BUTTON_LOG                  113
#define IDB_BITMAP_YTOP                 113
#define IDC_RADIO_FX                    114
#define IDC_LIST_FILES                  114
#define IDB_BITMAP_XCENTER              114
#define IDC_BUTTON_FILE                 115
#define IDB_BITMAP_XLEFT                115
#define IDC_BUTTON_FLODER               116
#define IDB_BITMAP_XRIGHT               116
#define IDC_BUTTON_ALLSEL               117
#define IDB_BITMAP_YBOTTOM              117
#define IDC_BUTTON_FX                   118
#define IDB_BITMAP_YCENTER              118
#define IDC_BUTTON_ALLNOTSEL            119
#define IDD_DIALOG_ALIGN                119
#define IDC_BUTTON_DEL                  120
#define IDB_BITMAP_AVERYTOP             120
#define IDC_BUTTON_CLEAR                121
#define IDB_BITMAP_AVERXCENTER          121
#define IDC_LIST_LOG                    122
#define IDB_BITMAP_AVERXLEFT            122
#define IDC_BUTTON_DELETE               122
#define IDC_TAB_PURGE                   123
#define IDB_BITMAP_AVERXRIGHT           123
#define IDC_BUTTON_UP                   123
#define IDC_STATIC_GROUP                124
#define IDB_BITMAP_AVERXRL              124
#define IDC_BUTTON_DOWN                 124
#define IDB_BITMAP_AVERYBOTTOM          125
#define IDC_BUTTON_TOP                  125
#define IDC_BUTTON_START                126
#define IDB_BITMAP_AVERYBT              126
#define IDC_BUTTON_BOTTOM               126
#define IDC_BUTTON_STOP                 127
#define IDB_BITMAP_AVERYCENTER          127
#define IDC_CHECK_AUTOSTART             128
#define IDD_DIALOG_AVERPOS              128
#define IDC_LIST_MOUSE                  129
#define IDC_COMBO_SAVETYPE              130
#define IDC_STATIC_SAVETYPE             131
#define IDC_EDIT_ID                     135
#define IDD_DIALOG_LAYERNORM            135
#define IDC_EDIT_REGKEY                 136
#define IDC_STATIC_TIP                  137
#define IDD_DIALOG_JOINDWG              137
#define IDC_STATIC_LINK                 138
#define IDD_DIALOG_SELECT               138
#define IDC_EDIT_DIS                    140
#define IDC_BUTTON1                     141
#define IDC_EDIT_NUM                    142
#define IDC_BUTTON4                     142
#define IDC_BUTTON5                     143
#define IDC_EDIT1                       145
#define IDC_RADIO1                      146
#define IDC_RADIO2                      147
#define IDC_CHECK1                      147
#define IDC_CHECK2                      148
#define IDC_CHECK3                      149
#define IDC_EDIT2                       149
#define IDC_EDIT_HOR                    149
#define IDC_CHECK4                      150
#define IDC_COMBO1                      150
#define IDC_EDIT3                       150
#define IDC_EDIT_VER                    150
#define IDC_CHECK5                      151
#define IDC_COMBO2                      151
#define IDC_TAB_MAIN                    151
#define IDC_EDIT4                       151
#define IDC_CHECK6                      152
#define IDC_COMBO3                      152
#define IDC_STATIC1                     152
#define IDC_CHECK7                      153
#define IDC_STATIC2                     153
#define IDC_CHECK8                      154
#define IDC_RADIO3                      154
#define IDC_STATIC3                     154
#define IDC_CHECK9                      155
#define IDC_STATIC4                     155
#define IDC_RADIO4                      156
#define IDC_CHECK10                     156
#define IDC_STATIC5                     156
#define IDC_STATIC6                     157
#define IDC_STATIC7                     158
#define IDC_STATIC8                     159
#define IDC_CHECK_EXPORTALL             162
#define IDC_LIST_MAIN                   163
#define IDC_RADIO_HOR                   164
#define IDC_RADIO_VER                   165
#define IDC_RADIO_HV                    166
#define IDC_COMBO_PAGE                  167
#define IDC_LIST_ITEMS                  168
#define IDC_LIST_LY                     200
#define IDD_DLG_LYSORT                  200
#define IDC_BTN_OK                      201
#define IDD_DIALOG_TABLEALIGN           201
#define IDC_BTN_APPLY                   202
#define IDD_DIALOG_EXPORTDIMENSION      202
#define IDC_CANCEL                      203

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         170
#define _APS_NEXT_SYMED_VALUE           123
#endif
#endif
