#!/bin/sh
# $Id: pphs,v 1.3 2002/02/21 21:49:28 giles Exp $
# Print the Primary Hint Stream from a linearized PDF file.  Usage:
#	pphs filename.pdf
# Output goes to stdout.

exec gs -q -dNODISPLAY -- pphs.ps "$@"
